---
- name: "My Kali"
  hosts: localhost
  connection: local
  roles:
    - role: "roles/install-tools"
    - role: "roles/configure-i3"
    - role: "roles/configure-ohmyzsh"
    - role: "roles/configure-vim"
