---
- name: "My Kali"
  hosts: localhost
  connection: local
  roles:
    - role: gantsign.oh-my-zsh
      users:
        - username: "{{ ansible_user_id }}"
          theme: robbyrussell
          plugins:
              - git
              - zsh-autosuggestions
              - sudo
              - google
              - copypath
              - copyfile
              - copybuffer
              - dirhistory
              - history
          update_mode: auto
          update_frequency: 10
    - role: "roles/install-tools"
    - role: "roles/configure-i3"
    - role: "roles/configure-alacritty"
    - role: "roles/configure-ohmyzsh"
    - role: gantsign.visual-studio-code
    - role: "roles/configure-vim"
      users:
        - username: "{{ ansible_user_id }}" 
          visual_studio_code_extensions:
            - streetsidesoftware.code-spell-checker
            - ms-python.python
            - DEVSENSE.phptools-vscode
            - GitHub.copilot-nightly
            - snyk-security.snyk-vulnerability-scanner
