---

- name: "Exporting path in .zshrc"
  shell:
    cmd: echo "export PATH=~/.local/bin:$PATH" >> ~/.zshrc
- name: "cloning zsh-syntax-highlighting"
  shell:
    cmd: git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
    - name: "cloning zsh-bat"
  shell:
    cmd: git clone https://github.com/fdellwing/zsh-bat.git $ZSH_CUSTOM/plugins/zsh-bat
- name: "add zsh-autosuggestions plugin to .zshrc"
  shell:
    cmd: sed -i "s/plugins\=(/plugins\=(zsh-autosuggestions\ zsh-syntax-highlighting\ zsh-bat\ history\ dirhistory\ copybuffer\ copyfile copypath\ web-search\ sudo\ /g" ~/.zshrc



